learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', include(admin.site.urls), #书本上的写法，会报错，将include（）取消就可以了
    url(r'^admin/', admin.site.urls),
    url(r'', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
]

learning_logs/urls.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-
# tester = 'Xiao'
"""定义learning_logs的url模式"""
from django.conf.urls import url
from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),

    # 显示所有的主题
    url(r'^topics/$', views.topics, name="topics"),

    # 显示特定主题
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # 用于添加新主题的网页
    url(r'^new_topic1/$', views.new_topic1, name='new_topic1'),
    #
    # 用于添加新条目的页面
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # 用于编辑条目的页面
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    # 用于删除条目的页面
    url(r'^delete_entry/(?P<entry_id>\d+)/$', views.delete_entry, name='delete_entry'),

    # 用于删除主题的页面
    url(r'^delete_topic/(?P<topic_id>\d+)/$', views.delete_topic, name='delete_topic'),

]

users/urls.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-
# tester = 'Xiao'
from django.conf.urls import url
from django.contrib.auth.views import LoginView  # 注意这是django2X的写法

from . import views

urlpatterns = [
    # 设置登录页面,LoginView.as_view后面要加上()
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),

    # 设置注销页面
    url(r'^logout/$', views.logout_view, name='logout'),

    # 设置注册页面
    url(r'^register/$', views.register, name='register'),
]

# from django.contrib.auth import login  #这是django1x的写法
# urlpatterns = [
#     # 设置登录页面
#     url(r'^login/$',login,{'template_name'='users/login.html'},name='login')
# ]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)  # 版本2x以上需要加上 on_delete=models.CASCADE

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    #
    def __str__(self):
        """返回模型的字符串表示"""
        # return self.text[:50] + "..."
        return self.text
    # def __str__(self):
    #     if len(self.text) > 50:        #设置当字数50以上时后面用省略号显示
    #         show_text = self.text[:50] + "..."
    #     else:
    #         show_text = self.text
    #     return show_text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-
# tester = 'Xiao'
from django import forms
from .models import Topic,Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required


def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')


@login_required  # 添加登录才可以访问的权限
def topics(request):
    """展示所有的主题"""
    # topics = Topic.objects.order_by('date_added')
    # 只允许访问登录用户自己的主题
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """显示单个主题及所有条目"""
    topic = Topic.objects.get(id=topic_id)

    # 确认主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic1(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据,对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic1 = form.save(commit=False)
            new_topic1.owner = request.user
            new_topic1.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic1.html', context)


@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # 未提交数据，创建一个新的表单
        form = EntryForm()
    else:
        # post提交的数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            # return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """编辑已有的条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初次请求时，用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # post提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    """删除已有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method == 'POST':
        # 初次请求时，用当前条目填充表单
        entry.delete()
        return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic}
    return render(request, 'learning_logs/delete_entry.html', context)


@login_required
def delete_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初次请求时，用当前条目填充表单
        topic.delete()
        return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'topic': topic}
    return render(request, 'learning_logs/topics.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """注册用户"""
    if request.method != "POST":
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)

    if form.is_valid():
        new_user = form.save()
        # 让用户自动登录，再重定向到主页
        authenticated_user = authenticate(username=new_user.username,
                                          password=request.POST['password1'])
        login(request, authenticated_user)
        return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!--<!DOCTYPE html>-->
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title> 学习日志 </title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body  style="background-color: LightGray;">
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top" style="background-color: CadetBlue">
           <div class="container">
               <div class="navbar-header">
                   <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                   </button>
                   <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
               </div>
               <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a>Hello, {{ user.username }}.</a></li>
                            <li><a href="{% url 'users:logout' %}">log out</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">register</a></li>
                            <li><a href="{% url 'users:login' %}">log in</a></li>
                        {% endif %}
                    </ul>
               </div><!--/.nav-collapse -->
           </div>
        </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}
            {% endblock header %}
        </div>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </div> <!-- /container -->
    </body>
</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ entry }}</a>
    </p>
    <form action="{% url 'learning_logs:delete_entry' entry.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">确认删除</button>
        <button name="submit">
            <a href="{% url 'learning_logs:topic' topic.id %}">取消</a>
        </button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">保存修改</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html'%}

{% block header %}
    <div>
        <h1>Track your learning</h1>
    </div>
{% endblock header %}
{%block content%}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a>
        to make your own Learning Log, and list the topics you're learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make an entry summarizing what you've learned.
    </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html'%}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>新增一个条目:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>保存条目</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic1.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic1' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit"  class="btn btn-primary">保存主题</button>
        <a href="{% url 'learning_logs:topics' %}" id="cancel" name="cancel" class="btn btn-default">取消</a>
        {% endbuttons %}

    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html'%}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content%}
    <p>
        <a href="{% url 'learning_logs:delete_topic' topic.id %}">删除主题</a>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <a href="{% url 'learning_logs:new_entry' topic.id %}">新增条目</a>
    </p>

    {%for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                     <small>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑条目</a>
                    </small>
                    <small>
                        <a href="{% url 'learning_logs:delete_entry' entry.id %}">删除条目</a>
                    </small>
                      <small>
                        <a href="{% url 'learning_logs:delete_entry' entry.id %}">测试一下</a>
                    </small>
                </h4>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div> <!-- panel -->
    {% empty %}
        There are no entries for this topic yet.
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html'%}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}
    <button>
            <a href="{% url 'learning_logs:new_topic1' %}">新增主题</a>
    </button>
    <ul>
        {%for topic in topics%}
        <li>
            <h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </h3>

        </li>
        {% empty%}
        <li> No topic have been added yet.</li>
        {% endfor %}
    </ul>


{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% block content %}
    {% if form.errors %}
        <p>您的账号或密码错误，请重试</p>
    {% endif %}
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token%}
        {{form.as_p}}

        <button name="submit">登录</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>

{% endblock%}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% block content %}
 <form method="post" action="{% url 'users:register' %}">
 {% csrf_token %}
 {{ form.as_p }}

 <button name="submit"> 确认 </button>
 <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
 </form>

{% endblock content %}